name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build
      run: make
